import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { PassThrough } from "node:stream";
import { stripVTControlCharacters } from "node:util";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { runAppUi } from "../src/commands/app-ui.js";
import { scanExportActions } from "../src/commands/scan-export-ui.js";
import { loadScanUi } from "../src/commands/scan-ui.js";
import { runUiBrowser, type UiTerminal } from "../src/commands/ui.js";
import * as week from "../src/commands/week.js";
import { buildProgram } from "../src/program.js";
import { priceSession, type RateTable } from "../src/pricing.js";
import { escapeHtml } from "../src/render/html.js";
import { ansiPalette, plainPalette, screenControl, uiThemeFor } from "../src/render/palette.js";
import { renderScanHtml, renderScanMarkdown, scanReportLines, scanUsageLines } from "../src/render/scan-report.js";
import { costCell, pricesChecked } from "../src/render/terminal/cost.js";
import { formatScan } from "../src/render/terminal/scan.js";
import { UI_MENU } from "../src/render/tui/menu.js";
import { navigateScan, renderScanUi, SCAN_WINDOWS, visibleScanned, type ScanUiData } from "../src/render/tui/scan.js";
import { initialState } from "../src/render/tui/state.js";
import { cellWidth } from "../src/render/tui/text.js";
import { summarizeScan, type ScannedSession } from "../src/scan.js";
import { appendSession, resolveStoreFile, zeroCost } from "../src/store.js";

const rates: RateTable = new Map([["known", { input: 1, cacheRead: 2, cacheCreation: 3, output: 4 }], ["second-model", { input: 3, cacheRead: 2, cacheCreation: 3, output: 4 }]]);
const scanned = (extra: Partial<ScannedSession> = {}): ScannedSession => ({ id: "local-row", repo: "/workspace/app", label: "First prompt", startedAt: "2026-10-05T12:00:00Z", endedAt: "2026-10-05T13:00:00Z", cost: { ...zeroCost(), turns: 2, apiCalls: 3, inputTokens: 1_000_000, cacheReadTokens: 2, cacheCreationTokens: 3, outputTokens: 4, model: "known", emptyTurns: 99 }, ...extra });
const data = (sessions = [scanned()], days = 14): ScanUiData => ({ sessions, days, rates, checked: "2026-10-01", repo: "app", root: "/transcripts", present: true, currentRepos: ["/workspace/app"] });
const browser = { returnToHome: true, render: renderScanUi, select: visibleScanned, navigate: navigateScan, windows: SCAN_WINDOWS };
const action = (key: string, options: week.WeekOptions) => scanExportActions(options).find(item => item.key === key)!;
function terminal(columns = 110, rows = 32) {
  const input = new PassThrough(); const output = new PassThrough(); Object.assign(input, { isTTY: true, isRaw: false, setRawMode: vi.fn() }); Object.assign(output, { isTTY: true, columns, rows });
  let text = ""; output.on("data", chunk => { text += String(chunk); }); return { input, io: { input, output } as unknown as UiTerminal, frame: () => text.split(screenControl.paint).at(-1) ?? "" };
}
const wait = async (term: ReturnType<typeof terminal>, text: string) => { await vi.waitFor(() => expect(term.frame()).toContain(text)); };
const selection = (usage: boolean, query = "") => `Local Claude Code transcripts: /transcripts · ${query ? `Search: ${query}` : "All loaded tool sessions"} · Usage details: ${usage ? "shown" : "hidden"}`;
let root: string; let options: { cwd: string; home: string; root: string; tmp: string; now: () => Date; adapters: never[] };
beforeEach(async () => { vi.stubEnv("TERM", "xterm"); root = await mkdtemp(path.join(tmpdir(), "session-scan-export-")); options = { cwd: path.join(root, "repo"), home: path.join(root, "store"), root: path.join(root, "projects"), tmp: root, now: () => new Date("2026-10-06T16:00:00Z"), adapters: [] }; await mkdir(options.cwd); });
afterEach(async () => { vi.unstubAllEnvs(); vi.restoreAllMocks(); await rm(root, { recursive: true, force: true }); });

describe("Native Scan usage and loaded exports", () => {
  it("keeps the four measured counters separate, preserves unknown-model tokens and prices multiple models through the native rule", () => {
    for (const cost of [scanned().cost, { ...scanned().cost, model: "future-model" }, { ...scanned().cost, modelTokens: { known: { inputTokens: 500_000, cacheReadTokens: 2, cacheCreationTokens: 3, outputTokens: 4 }, "second-model": { inputTokens: 500_000, cacheReadTokens: 0, cacheCreationTokens: 0, outputTokens: 0 } } }]) {
      const lines = scanUsageLines(cost, rates); expect(lines).toContain("Input tokens: 1,000,000"); expect(lines).toContain("Cache read tokens: 2"); expect(lines).toContain("Cache creation tokens: 3"); expect(lines).toContain("Output tokens: 4"); expect(lines).toContain(`Cost: ${costCell(cost, priceSession(cost, rates))}`); expect(lines).toContain("Turns that changed no files: not measured; no diff recorded."); expect(lines.join("\n")).not.toContain("99");
    }
    const zero = { ...zeroCost(), model: "known", turns: 1 }; expect(scanUsageLines(zero, rates)).toContain("Cost: $0.00"); expect(scanUsageLines(zero, rates, "2026-10-01").at(-1)).toBe(pricesChecked("2026-10-01")); expect(scanUsageLines({ ...zero, model: "future" }, rates, "2026-10-01").join("\n")).not.toContain("2026-10-01");
  });
  it("keeps no-turn, missing-token, null-turn and billing-unknown coverage distinct from absent model prices", () => {
    const gaps = [{ ...zeroCost(), model: "known", apiCalls: 1 }, { ...scanned().cost, untokenedTurns: 1 }, { ...scanned().cost, turnTokens: [null], turnModels: [null] }, { ...scanned().cost, turnTokens: [{ inputTokens: 0, cacheReadTokens: 0, cacheCreationTokens: 1, outputTokens: 0 }], turnModels: ["known"] }];
    for (const cost of gaps) {
      const rows = [scanned(), scanned({ id: "gap-row", cost })]; const lines = scanReportLines(rows, 14, rates, ["Full transcript retained"], undefined, "2026-10-01"); expect(lines).toContain("Full transcript retained"); expect(lines.at(-1)).toContain("Money total unavailable"); expect(lines.join("\n")).toContain("gap-row"); expect(lines.join("\n")).not.toMatch(/\$|dearest|rates\.json|2026-10-01/u);
      const usage = scanUsageLines(cost, rates); expect(usage.join("\n")).not.toContain("$0.00"); if (cost.turns === 0) expect(usage.join("\n")).toContain("Usage not captured"); else if ((cost.untokenedTurns ?? 0) > 0 || cost.turnTokens?.some(turn => turn === null)) expect(usage.filter(line => /^(Input|Cache read|Cache creation|Output) tokens:/u.test(line)).every(line => line.endsWith("not fully captured"))).toBe(true); else expect(usage.join("\n")).toContain("billing unverified");
    }
    const unpriced = scanReportLines([scanned({ cost: { ...scanned().cost, model: "future-model" } })], 14, rates).join("\n"); expect(unpriced).toContain("future-model"); expect(unpriced).toContain("rates.json"); expect(unpriced).not.toContain("$0.00");
  });
  it("retains canonical aggregate lines, inserts full details before closing money and dates only actual figures", () => {
    const rows = [scanned({ landed: true }), scanned({ id: "unknown", landed: undefined })]; const report = summarizeScan(rows, rates, 14); const native = formatScan(report, plainPalette); const detailed = scanReportLines(rows, 14, rates, ["COMPLETE DETAIL"]); for (const line of native) expect(detailed).toContain(line); expect(detailed.indexOf("COMPLETE DETAIL")).toBeLessThan(detailed.findLastIndex(line => line.includes("spent"))); expect(detailed.at(-1)).toBe(native.at(-1)); expect(formatScan(report, plainPalette, undefined, [])).toEqual(native);
    expect(scanReportLines(rows, 14, rates, [], undefined, "2026-10-01").at(-1)).toBe(pricesChecked("2026-10-01")); for (const usage of [false, true]) { const empty = renderScanMarkdown([], 14, rates, "Search: missing", usage, "2026-10-01"); expect(empty).toContain("Search: missing"); expect(empty).not.toMatch(/\$0\.00|2026-10-01/u); }
  });
  it("copies exact full Markdown and writes inert private HTML for the loaded range, unknown directory and reader provenance", async () => {
    const label = '<script>alert("x")</script>\n<img src="https://evil.invalid" onerror="alert(1)">\n`````\nFULL PROMPT'; const row = scanned({ id: "unknown-directory", repo: "", label }); const input = { ...data([scanned(), row], 30), restriction: "/bound directory" }; const state = { ...initialState(), query: "repo:unknown", usage: true }; const copy = vi.fn(async (_text: string) => {}); const launch = vi.fn(async (_file: string) => {}); const provenance = "Local Claude Code transcripts: /transcripts · Reader limited to directory: /bound directory · Search: repo:unknown · Usage details: shown";
    const weekFile = await week.writeWeekPage("existing Week page", options); await action("c", { ...options, copy }).run(input, state); expect(copy).toHaveBeenCalledWith(renderScanMarkdown([row], 30, rates, provenance, true, input.checked)); expect(copy.mock.calls[0]![0]).toContain(label); expect(copy.mock.calls[0]![0]).toContain("``````text");
    await action("h", { ...options, launch }).run(input, state); const file = launch.mock.calls[0]![0]; const html = await readFile(file, "utf8"); expect(html).toBe(renderScanHtml([row], 30, rates, provenance, true, input.checked)); expect(path.basename(file)).toMatch(/^session-scan-/u); expect((await stat(file)).mode & 0o777).toBe(0o600); expect(await readFile(weekFile, "utf8")).toBe("existing Week page"); for (const line of label.split("\n")) expect(html).toContain(escapeHtml(line)); expect(html).not.toMatch(/<(?:script|img|iframe|link)\b|(?:src|href)="https?:|@import|url\(/iu);
  });
  it("refuses invalid repository queries and aborted invocations before clipboard, file or browser effects", async () => {
    const copy = vi.fn(async (_text: string) => {}); const launch = vi.fn(async (_file: string) => {}); for (const query of ["repo:invalid", "repo:", "repo:all repo:current"]) for (const key of ["c", "h"]) await expect(action(key, { ...options, copy, launch }).run(data(), { ...initialState(), query })).rejects.toThrow("Fix the search");
    const aborted = new AbortController(); aborted.abort(); for (const key of ["c", "h"]) await expect(action(key, { ...options, copy, launch }).run(data(), initialState(), undefined, aborted.signal)).rejects.toThrow(); expect(copy).not.toHaveBeenCalled(); expect(launch).not.toHaveBeenCalled(); expect(await readdir(root)).toEqual(["repo"]);
  });
  it("retries clipboard failures and preserves the HTML file and complete recovery path after launch failure", async () => {
    const copy = vi.fn().mockRejectedValueOnce(new Error("clipboard unavailable")).mockResolvedValue(undefined); const term = terminal(); const running = runUiBrowser(data(), async () => data(), plainPalette, term.io, { ...browser, actions: scanExportActions({ ...options, copy }) }); term.input.write("c"); await wait(term, "clipboard unavailable"); term.input.write("c"); await wait(term, "Copied Markdown"); expect(copy).toHaveBeenCalledTimes(2); term.input.write("q"); await running;
    const launch = vi.fn(async (_file: string) => { throw new Error("browser unavailable"); }); await expect(action("h", { ...options, launch }).run(data(), initialState())).rejects.toThrow("HTML saved. Open"); const file = launch.mock.calls[0]![0]; expect(await readFile(file, "utf8")).toBe(renderScanHtml(data().sessions, 14, rates, selection(false), false, data().checked));
  });
  it("treats usage/export/range letters as search text and keeps Help, Ctrl and paste from invoking them", async () => {
    const state = { ...initialState(), scroll: 8 }; expect(navigateScan(state, { name: "u" }, 1, 20)).toMatchObject({ usage: true, scroll: 0 }); expect(navigateScan(state, { name: "u", ctrl: true }, 1, 20)).toMatchObject({ usage: false, scroll: 3 }); expect(navigateScan({ ...state, help: true }, { name: "u" }, 1, 20).usage).toBe(false);
    const copy = vi.fn(async (_text: string) => {}); const launch = vi.fn(async (_file: string) => {}); const term = terminal(); const running = runUiBrowser(data(), async () => data(), plainPalette, term.io, { ...browser, actions: scanExportActions({ ...options, copy, launch }) }); term.input.write("/uchw\r"); expect(term.frame()).toContain("> uchw"); term.input.emit("keypress", "", { name: "escape" }); term.input.write("?uchw"); term.input.emit("keypress", "", { name: "escape" }); term.input.emit("keypress", "", { name: "h", ctrl: true }); term.input.emit("keypress", "", { sequence: "\u001b[200~" }); term.input.write("uchw"); term.input.emit("keypress", "", { sequence: "\u001b[201~" }); term.input.write("q"); expect((await running).state.usage).toBe(false); expect(copy).not.toHaveBeenCalled(); expect(launch).not.toHaveBeenCalled(); expect(await readdir(root)).toEqual(["repo"]);
  });
  it("serializes exports with range reloads and freezes matching rows, range and usage at invocation", async () => {
    let finishCopy!: () => void; let finishRange!: (value: ScanUiData) => void; const copy = vi.fn<(text: string) => Promise<void>>().mockImplementationOnce(() => new Promise(resolve => { finishCopy = resolve; })).mockResolvedValue(undefined); const refresh = vi.fn(() => new Promise<ScanUiData>(resolve => { finishRange = resolve; })); const launch = vi.fn(async (_file: string) => {}); const input = data([scanned(), scanned({ id: "other", repo: "/other" })]); const term = terminal(); const running = runUiBrowser(input, refresh, plainPalette, term.io, { ...browser, actions: scanExportActions({ ...options, copy, launch }) });
    term.input.write("ucwhp"); expect(copy).toHaveBeenCalledTimes(1); expect(refresh).not.toHaveBeenCalled(); finishCopy(); await wait(term, "Copied Markdown"); expect(copy.mock.calls[0]![0]).toBe(renderScanMarkdown(input.sessions, 14, rates, selection(true), true, input.checked)); term.input.write("wch"); expect(refresh).toHaveBeenCalledTimes(1); expect(copy).toHaveBeenCalledTimes(1); finishRange({ ...input, days: 30 }); await wait(term, "Refreshed."); term.input.write("c"); await wait(term, "Copied Markdown"); expect(copy.mock.calls[1]![0]).toBe(renderScanMarkdown([input.sessions[0]!], 30, rates, selection(true, "repo:current"), true, input.checked)); expect(launch).not.toHaveBeenCalled(); term.input.write("q"); expect((await running).state.usage).toBe(true);
  });
  it("does not launch a page or repaint Home when its pending save finishes after Back", async () => {
    let saved!: (file: string) => void; vi.spyOn(week, "writeWeekPage").mockImplementationOnce(() => new Promise(resolve => { saved = resolve; })); const launch = vi.fn(async (_file: string) => {}); const term = terminal(); const running = runUiBrowser(data(), async () => data(), plainPalette, term.io, { ...browser, actions: scanExportActions({ ...options, launch }) }); term.input.write("hq"); await running; const home = runAppUi({ repo: "app", branch: "main", home: {} }, plainPalette, term.io); const frame = term.frame(); saved(path.join(root, "late.html")); await new Promise(resolve => setImmediate(resolve)); expect(launch).not.toHaveBeenCalled(); expect(term.frame()).toBe(frame); term.input.write("q"); await home;
  });
  it("bounds usage/export controls and complete recovery paths at 60×20, with reachable aggregate figures and colour parity", () => {
    const notice = `HTML saved. Open /private/tmp/${"long-directory/".repeat(15)}scan.html yourself.`; for (const state of [{ ...initialState(), usage: true }, { ...initialState(), usage: true, help: true }, { ...initialState(), usage: true, query: "repo:" + "invalid".repeat(60) }]) {
      const plain = renderScanUi(data(), state, 60, 20, plainPalette, notice); const colour = renderScanUi(data(), state, 60, 20, ansiPalette, notice, uiThemeFor({ isTTY: true, env: { TERM: "xterm" } })); expect(plain.lines.length).toBeLessThanOrEqual(19); expect(plain.lines.every(line => cellWidth(line) <= 59)).toBe(true); expect(colour.lines.map(stripVTControlCharacters)).toEqual(plain.lines); for (const key of ["u", "c", "h", "w", "p"]) expect(plain.lines.join("\n")).toContain(`[${key}]`);
      const start = plain.lines.findIndex(line => line.includes("HTML saved. Open")); const end = plain.lines.findLastIndex(line => /^─+$/u.test(line.trim())); const pages = Array.from({ length: plain.maxScroll + 1 }, (_, scroll) => renderScanUi(data(), { ...state, scroll }, 60, 20, plainPalette, notice).lines); const body = [...pages.map(lines => lines[start]!), ...pages.at(-1)!.slice(start + 1, end)].join("").replace(/\s/gu, ""); expect(body).toContain(notice.replace(/\s/gu, "")); if (!state.help && !state.query) { expect(body).toContain("ACTIVITYREPORT"); expect(body).toContain(pricesChecked("2026-10-01").replace(/\s/gu, "")); expect(body).toContain(costCell(scanned().cost, priceSession(scanned().cost, rates)).replace(/\s/gu, "")); }
    }
  });
  it("reaches every usage counter and the aggregate through actual PgDown keypresses at 60×20", async () => {
    const term = terminal(60, 20); const running = runUiBrowser(data(), async () => data(), plainPalette, term.io, { ...browser, state: { ...initialState(), usage: true } }); const frames: string[] = [];
    for (let page = 0; page < 100; page++) { const frame = term.frame(); frames.push(frame); term.input.write("\u001b[6~"); await new Promise(resolve => setImmediate(resolve)); if (term.frame() === frame) break; }
    const text = frames.join("\n"); for (const line of ["Input tokens: 1,000,000", "Cache read tokens: 2", "Cache creation tokens: 3", "Output tokens: 4", "ACTIVITY REPORT"]) expect(text).toContain(line); expect(text.replace(/\s/gu, "")).toContain(pricesChecked("2026-10-01").replace(/\s/gu, "")); term.input.write("q"); await running;
  });
  it("exports through the real workspace and remembers usage/range/project without changing transcript or signed bytes", async () => {
    const directory = path.join(options.root, "project"); await mkdir(directory, { recursive: true }); const source = path.join(directory, "real-row.jsonl"); await writeFile(source, [JSON.stringify({ type: "user", timestamp: "2026-10-05T12:00:00Z", cwd: options.cwd, message: { role: "user", content: "Recorded prompt" } }), JSON.stringify({ type: "assistant", timestamp: "2026-10-05T12:00:00Z", cwd: options.cwd, requestId: "real-call", message: { role: "assistant", model: "future-model", content: [{ type: "text", text: "reply" }], usage: { input_tokens: 20, output_tokens: 3, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 } } })].join("\n") + "\n"); await appendSession({ intent: "signed goal", startCommit: "base", startedAt: "2026-10-01T12:00:00Z", endedAt: "2026-10-01T13:00:00Z" }, options); const ledger = await resolveStoreFile(options); const before = await readFile(ledger); const original = await readFile(source); const copy = vi.fn(async (_text: string) => {}); const launch = vi.fn(async (_file: string) => {}); const term = terminal(); const open = () => term.input.write("m" + "\u001b[B".repeat(UI_MENU.findIndex(item => item.screen === "scan")) + "\r");
    const running = buildProgram({ ...options, copy, launch, appTerminal: term.io, palette: plainPalette }).parseAsync([], { from: "user" }); await wait(term, "OVERVIEW"); open(); await wait(term, "TOOL ACTIVITY"); term.input.write("w"); await wait(term, "Refreshed."); term.input.write("puc"); await wait(term, "Copied Markdown"); term.input.write("h"); await wait(term, "Opened HTML"); const loaded = await loadScanUi(7, options); const provenance = `Local Claude Code transcripts: ${options.root} · Search: repo:current · Usage details: shown`; expect(copy).toHaveBeenCalledWith(renderScanMarkdown(loaded.sessions, 7, loaded.rates, provenance, true, loaded.checked)); expect(await readFile(launch.mock.calls[0]![0], "utf8")).toBe(renderScanHtml(loaded.sessions, 7, loaded.rates, provenance, true, loaded.checked)); term.input.write("q"); await wait(term, "OVERVIEW"); open(); await wait(term, "TOOL ACTIVITY"); expect(term.frame()).toContain("[u] Usage: hide"); expect(term.frame()).toContain("repo:current"); expect(term.frame()).toContain("last 7 days"); term.input.end(); await running; expect(await readFile(ledger)).toEqual(before); expect(await readFile(source)).toEqual(original);
  });
});
